## Donovan Mosheh Ramirez Trejo

In [192]:
import numpy as np
import pandas as pd

In [7]:
def read_data(route):
    return pd.read_csv(route)

In [38]:
data = read_data("datos_EM.csv")
data

x1   x2  x3    x4   x5      y
0   35  0.3  82  0.20  0.3   76.5
1   35  0.3  82  0.30  0.5   76.0
2   35  0.3  88  0.20  0.5   79.9
3   35  0.3  88  0.30  0.3   83.5
4   35  0.7  82  0.20  0.5   89.5
5   35  0.7  82  0.30  0.3   54.2
6   35  0.7  88  0.20  0.3   85.7
7   35  0.7  88  0.30  0.5   99.5
8   55  0.3  82  0.20  0.5   89.4
9   55  0.3  82  0.30  0.3   97.5
10  55  0.3  88  0.20  0.3  103.2
11  55  0.3  88  0.30  0.5  108.7
12  55  0.7  82  0.20  0.3  115.2
13  55  0.7  82  0.30  0.5  111.5
14  55  0.7  88  0.20  0.5  102.3
15  55  0.7  88  0.30  0.3  108.1
16  25  0.5  85  0.25  0.4   80.2
17  65  0.5  85  0.25  0.4   89.1
18  45  0.1  85  0.25  0.4   77.2
19  45  0.9  85  0.25  0.4   85.1
20  45  0.5  79  0.25  0.4   71.5
21  45  0.5  91  0.25  0.4   84.5
22  45  0.5  85  0.15  0.4   77.5
23  45  0.5  85  0.35  0.4   79.2
24  45  0.5  85  0.25  0.2   71.0
25  45  0.5  85  0.25  0.6   90.2

In [39]:
X = pd.DataFrame({"x0":[1 for _ in range(data.shape[0])]})
Y = data["y"]
del data["y"]
X = pd.concat([X,data],axis=1)
X

x0  x1   x2  x3    x4   x5
0    1  35  0.3  82  0.20  0.3
1    1  35  0.3  82  0.30  0.5
2    1  35  0.3  88  0.20  0.5
3    1  35  0.3  88  0.30  0.3
4    1  35  0.7  82  0.20  0.5
5    1  35  0.7  82  0.30  0.3
6    1  35  0.7  88  0.20  0.3
7    1  35  0.7  88  0.30  0.5
8    1  55  0.3  82  0.20  0.5
9    1  55  0.3  82  0.30  0.3
10   1  55  0.3  88  0.20  0.3
11   1  55  0.3  88  0.30  0.5
12   1  55  0.7  82  0.20  0.3
13   1  55  0.7  82  0.30  0.5
14   1  55  0.7  88  0.20  0.5
15   1  55  0.7  88  0.30  0.3
16   1  25  0.5  85  0.25  0.4
17   1  65  0.5  85  0.25  0.4
18   1  45  0.1  85  0.25  0.4
19   1  45  0.9  85  0.25  0.4
20   1  45  0.5  79  0.25  0.4
21   1  45  0.5  91  0.25  0.4
22   1  45  0.5  85  0.15  0.4
23   1  45  0.5  85  0.35  0.4
24   1  45  0.5  85  0.25  0.2
25   1  45  0.5  85  0.25  0.6

## Operaciones

$X^{T}X$

In [45]:
xT_x = np.dot(np.array(X).transpose(),np.array(X))
xT_x

array([[2.60000e+01, 1.17000e+03, 1.30000e+01, 2.21000e+03, 6.50000e+00,
        1.04000e+01],
       [1.17000e+03, 5.50500e+04, 5.85000e+02, 9.94500e+04, 2.92500e+02,
        4.68000e+02],
       [1.30000e+01, 5.85000e+02, 7.46000e+00, 1.10500e+03, 3.25000e+00,
        5.20000e+00],
       [2.21000e+03, 9.94500e+04, 1.10500e+03, 1.88066e+05, 5.52500e+02,
        8.84000e+02],
       [6.50000e+00, 2.92500e+02, 3.25000e+00, 5.52500e+02, 1.68500e+00,
        2.60000e+00],
       [1.04000e+01, 4.68000e+02, 5.20000e+00, 8.84000e+02, 2.60000e+00,
        4.40000e+00]])

$(X^{T}X)^{-1}$

In [49]:
inv_xT_x = np.linalg.inv(xT_x)
inv_xT_x

array([[ 3.63000356e+01, -1.87500000e-02, -5.20833333e-01,
        -3.93518519e-01, -4.16666667e+00, -1.66666667e+00],
       [-1.87500000e-02,  4.16666667e-04,  0.00000000e+00,
         1.31376391e-17,  0.00000000e+00,  0.00000000e+00],
       [-5.20833333e-01, -9.13033455e-32,  1.04166667e+00,
         0.00000000e+00,  2.85322955e-29, -3.85494106e-15],
       [-3.93518519e-01, -0.00000000e+00, -0.00000000e+00,
         4.62962963e-03, -0.00000000e+00, -0.00000000e+00],
       [-4.16666667e+00, -7.30426764e-31,  2.85322955e-29,
        -1.60112123e-29,  1.66666667e+01, -3.08395285e-14],
       [-1.66666667e+00,  9.86864911e-17, -3.85494106e-15,
         2.16324269e-15, -3.08395285e-14,  4.16666667e+00]])

$X^{T}y$

In [50]:
xT_y = np.dot(np.array(X).transpose(),Y)
xT_y

array([  2286.2  , 104968.   ,   1156.52 , 194588.3  ,    571.585,
          921.61 ])

$(X^{T}X)^{-1}X^{T}y$ ====> $b$

In [51]:
inv_xT_x_xT_y = np.dot(inv_xT_x,xT_y)
inv_xT_x_xT_y

array([-73.08311966,   0.87041667,  13.97916667,   1.20972222,
         0.58333333,  29.70833333])

In [167]:
class model:
    
    def __init__(self,params,variables):
        self.params = params
        self.variables = variables
        self.equation = self.__createEquation(params,variables)
        self.model = self.__dictEquation(params,variables)
        
    def __repr__(self):
        return "y = "+self.equation[:-2]
    
    def __getitem__(self,key):
        return self.equation.split("+")[key]
    
    def __createEquation(self,params,variables):        
        modelEquation = ""
        for j,i in enumerate(params):
            modelEquation += str(i) + (variables[j-1] if j != 0 and j-1 < len(variables) else "") + " " + "+ "
        return modelEquation[:-1]
    
    def __dictEquation(self,params,variables):
        modelDict = {}
        for i,j in zip(params[1:],variables):
            modelDict[j] = i
        return modelDict
    
    def predict(self,X):
        """
        X: DataFrame
        
        return: np.array with predictions
        """
        bias = float(self.equation.split("+")[0])
        result = 0
        for i in self.model:
            result += self.model[i]*X[i]
        return np.array(result+bias)
        

$y=-73.08+0.87x1+13.97x2+1.2x3+0.58x4+29.7x5$

In [168]:
modelToPredict = model(inv_xT_x_xT_y,list(data.columns))
modelToPredict

y = -73.08311965811663 + 0.8704166666666708x1 + 13.979166666666828x2 + 1.20972222222224x3 + 0.5833333333339397x4 + 29.708333333332575x5

### Predicciones

In [169]:
yP = modelToPredict.predict(data)
yP

array([ 69.80160256,  75.80160256,  83.00160256,  77.11826923,
        81.3349359 ,  75.45160256,  82.65160256,  88.65160256,
        93.15160256,  87.26826923,  94.46826923, 100.46826923,
        92.80160256,  98.80160256, 106.00160256, 100.11826923,
        70.5224359 , 105.33910256,  82.33910256,  93.5224359 ,
        80.6724359 ,  95.18910256,  87.8724359 ,  87.98910256,
        81.98910256,  93.8724359 ])

In [170]:
u = np.array(Y-yP)
u

array([  6.69839744,   0.19839744,  -3.10160256,   6.38173077,
         8.1650641 , -21.25160256,   3.04839744,  10.84839744,
        -3.75160256,  10.23173077,   8.73173077,   8.23173077,
        22.39839744,  12.69839744,  -3.70160256,   7.98173077,
         9.6775641 , -16.23910256,  -5.13910256,  -8.4224359 ,
        -9.1724359 , -10.68910256, -10.3724359 ,  -8.78910256,
       -10.98910256,  -3.6724359 ])

In [171]:
Sr_2 = np.sum((Y-yP)**2)/(data.shape[0]-(len(data.columns)+1))
Sr_2

135.7916650641026

## Calculando los intervalos de confianza

Grados de libertad = 20

Tstudent_20_0.95 = 1.72

In [184]:
var_bG = Sr_2*inv_xT_x
pd.DataFrame(var_bG)

0             1             2             3             4  \
0  4929.242278 -2.546094e+00 -7.072483e+01 -5.343653e+01 -5.657986e+02   
1    -2.546094  5.657986e-02  0.000000e+00  1.783982e-15  0.000000e+00   
2   -70.724826 -1.239823e-29  1.414497e+02  0.000000e+00  3.874448e-27   
3   -53.436535 -0.000000e+00 -0.000000e+00  6.286651e-01 -0.000000e+00   
4  -565.798604 -9.918587e-29  3.874448e-27 -2.174189e-27  2.263194e+03   
5  -226.319442  1.340080e-14 -5.234689e-13  2.937503e-13 -4.187751e-12   

              5  
0 -2.263194e+02  
1  0.000000e+00  
2 -5.234689e-13  
3 -0.000000e+00  
4 -4.187751e-12  
5  5.657986e+02

In [183]:
IC_bG_max = []
IC_bG_min = []
IC_bG = []

for i in range(var_bG.shape[0]):
    IC_bG_max.append(inv_xT_x_xT_y[i]+(1.72*((var_bG[i][i])**(1/2))))
    IC_bG_min.append(inv_xT_x_xT_y[i]-(1.72*((var_bG[i][i])**(1/2))))
    IC_bG.append((IC_bG_min[i],IC_bG_max[i]))

IC_bG

[(-193.841847518196, 47.67560820196273),
 (0.461288497096689, 1.2795448362366526),
 (-6.4772418118322825, 34.43557514516594),
 (-0.1540383430110428, 2.5734827874555224),
 (-81.2423005806624, 82.40896724733028),
 (-11.20448362366551, 70.62115029033066)]